local groups = {
    Comment = { ctermfg = "DarkGray", cterm = { italic = true } },
    Constant = { ctermfg = "Magenta" },
    String = { ctermfg = "Green" },
    Character = { ctermfg = "Green" },
    Number = { ctermfg = "Yellow" },
    Boolean = { ctermfg = "Yellow" },
    Float = { ctermfg = "Yellow" },
    Identifier = { ctermfg = "Cyan" },
    Function = { ctermfg = "Cyan" },
    Statement = { ctermfg = "Blue" },
    Conditional = { ctermfg = "Blue" },
    Repeat = { ctermfg = "Blue" },
    Label = { ctermfg = "Blue" },
    Operator = { ctermfg = "Blue" },
    Keyword = { ctermfg = "Blue" },
    Exception = { ctermfg = "Blue" },
    PreProc = { ctermfg = "Magenta" },
    Include = { ctermfg = "Magenta" },
    Define = { ctermfg = "Magenta" },
    Macro = { ctermfg = "Magenta" },
    PreCondit = { ctermfg = "Magenta" },
    Type = { ctermfg = "Yellow" },
    StorageClass = { ctermfg = "Yellow" },
    Structure = { ctermfg = "Yellow" },
    Typedef = { ctermfg = "Yellow" },
    Special = { ctermfg = "Red" },
    SpecialChar = { ctermfg = "Red" },
    Tag = { ctermfg = "Cyan" },
    Delimiter = { ctermfg = "White" },
    SpecialComment = { ctermfg = "DarkGray" },
    Debug = { ctermfg = "Red" },
    Underlined = { ctermfg = "Cyan", cterm = { underline = true } },
    Error = { ctermfg = "Red", cterm = { bold = true } },
    Todo = { ctermfg = "Yellow", cterm = { bold = true } },
    DiagnosticError = { ctermfg = "Red" },
    DiagnosticWarn = { ctermfg = "Yellow" },
    DiagnosticInfo = { ctermfg = "Cyan" },
    DiagnosticHint = { ctermfg = "Blue" },
}

for group, opts in pairs(groups) do
    vim.api.nvim_set_hl(0, group, opts)
end

local links = {
    ["@comment"] = "Comment",
    ["@constant"] = "Constant",
    ["@constant.builtin"] = "Constant",
    ["@string"] = "String",
    ["@string.special"] = "SpecialChar",
    ["@character"] = "Character",
    ["@number"] = "Number",
    ["@number.float"] = "Float",
    ["@boolean"] = "Boolean",
    ["@variable"] = "Normal",
    ["@variable.parameter"] = "Identifier",
    ["@property"] = "Identifier",
    ["@function"] = "Function",
    ["@function.call"] = "Function",
    ["@function.builtin"] = "Function",
    ["@method"] = "Function",
    ["@method.call"] = "Function",
    ["@constructor"] = "Function",
    ["@keyword"] = "Keyword",
    ["@keyword.function"] = "Keyword",
    ["@keyword.return"] = "Keyword",
    ["@keyword.conditional"] = "Conditional",
    ["@keyword.repeat"] = "Repeat",
    ["@operator"] = "Operator",
    ["@type"] = "Type",
    ["@type.builtin"] = "Type",
    ["@module"] = "Include",
    ["@punctuation.delimiter"] = "Delimiter",
    ["@punctuation.bracket"] = "Delimiter",
    ["@tag"] = "Tag",
    ["@tag.attribute"] = "Identifier",
    ["@tag.delimiter"] = "Delimiter",
    ["@lsp.type.comment"] = "Comment",
    ["@lsp.type.string"] = "String",
    ["@lsp.type.number"] = "Number",
    ["@lsp.type.keyword"] = "Keyword",
    ["@lsp.type.function"] = "Function",
    ["@lsp.type.method"] = "Function",
    ["@lsp.type.type"] = "Type",
    ["@lsp.type.class"] = "Type",
    ["@lsp.type.enum"] = "Type",
    ["@lsp.type.interface"] = "Type",
    ["@lsp.type.parameter"] = "Identifier",
    ["@lsp.type.variable"] = "Normal",
    ["@lsp.type.property"] = "Identifier",
}

for group, link in pairs(links) do
    vim.api.nvim_set_hl(0, group, { link = link })
end
