#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '\.php$')

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

echo "Running Rector on staged PHP files..."
echo "$STAGED_FILES" | xargs -L1 -P$(sysctl -n hw.ncpu) rector process --dry-run --quiet

if [ $? -ne 0 ]; then
  echo "Rector found issues in staged files."
  exit 1
fi

echo "All PHP files processed successfully."