os:
  editPreset: "nvim"
gui:
  showCommandLog: false # remove lower-left command log
  showBottomLine: false # hide key-hint/status line at the very bottom
  showRandomTip: false # no tips on startup
  showListFooter: false # no “5 of 20” footer in list views
  showPanelJumps: false # don’t print “1-5” window-jump hints
  commitLength:
    show: false # turn off commit-length ruler
  expandFocusedSidePanel: true
  showFileTree: true
  showRootItemInFileTree: false
  theme:
    activeBorderColor:
      - "#04a5e5"
      - bold
    inactiveBorderColor:
      - "#6c6f85"
    optionsTextColor:
      - "#1e66f5"
    selectedLineBgColor:
      - "#cdd0da"
    selectedRangeBgColor:
      - "#e8e8e8"
    cherryPickedCommitBgColor:
      - "#bcc0cc"
    cherryPickedCommitFgColor:
      - "#04a5e5"
    unstagedChangesColor:
      - "#d20f39"
    defaultFgColor:
      - "#4c4f69"
    searchingActiveBorderColor:
      - "#df8e1d"

  authorColors:
    "*": "#7287fd"

keybinding:
  universal:
    select: "a" # Stage/select (was <space>)
  files:
    toggleStagedAll: "A" # Stage all files
    stashAllChanges: "s" # Stash changes
    amendLastCommit: "m" # Amend last commit (suggested: 'm' for "modify")
