os:
  editPreset: "nvim"
gui:
  showCommandLog: false # remove lower-left command log
  showBottomLine: false # hide key-hint/status line at the very bottom
  showRandomTip: false # no tips on startup
  showListFooter: false # no “5 of 20” footer in list views
  showPanelJumps: false # don’t print “1-5” window-jump hints
  commitLength:
    show: false # turn off commit-length ruler
  expandFocusedSidePanel: true
  showFileTree: true
  showRootItemInFileTree: false

keybinding:
  universal:
    select: "a" # Stage/select (was <space>)
  files:
    toggleStagedAll: "A" # Stage all files
    stashAllChanges: "s" # Stash changes
    amendLastCommit: "m" # Amend last commit (suggested: 'm' for "modify")
